### ISSUE TITLE
remove acquisition group from config

### ISSUE THREAD

**Issue by wakonig** [bec-project/bec#98]
# Goal 

Instead of defining the acquisition group, the ophyd signature could be used to retrieve e.g. a list of motors.

# example device

A device within the config could look as follows! 
```
undulator:
  description: 'Undulator' #optional
  deviceClass: X07MAUndulator
  deviceConfig: 
    prefix: 'X07MA-ID:' # add here more configurable signals, e.g. DDG or Galil limits
  userParameter: # Optional
    in: 15.4
    out: 16.3
  readoutPriority: baseline
  onFailure: retry
  enabled: true
  readonly: false
```
 Migrated from GitLab issue https://gitlab.psi.ch/bec/bec/-/issues/98
